### ISSUE TITLE
 TypeError: Cannot destructure property `Resolver` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by ahelord** [Cvmcosta/ltijs-examples#2]
When I run the example locally and install version ltijs 4.0.7 it fails with this error

```
               Resolver: AsyncResolver
                ^

TypeError: Cannot destructure property `Resolver` of 'undefined' or 'null'.

**Comment by Cvmcosta** [comment]
Hello, can you walk me through the steps that led to this error? And what is the version of node you are using?

**Comment by ahelord** [comment]
this error throw with Node 10.1.0 and not 12.16.3
